title: Samuel Schwab # name of the site
author: Samuel Schwab # name of site's author
email: s.schwab@lic.leidenuniv.nl # email of site's author
url: samuelschwab.com # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  I look at proteins and stuff.

permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

# Build settings
theme: no-style-please

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-compose
  - jekyll-sitemap

include:
  - _pages

jektex:
  cache_dir: ".jektex-cache"
  ignore: ["*.xml"]
  silent: true
  macros:
    - ["\\Q", "\\mathbb{Q}"]
    - ["\\C", "\\mathbb{C}"]